### PR TITLE
#106 Add polling control start/stop events

### PR DESCRIPTION
**Pull request by vanboom**
In an attempt to gain more control over the start and stop of polling.  I have added two events:  `async-start`, `async-stop` for your consideration.

### CODE REVIEW

**Comment by nikolalsvk** [comment]
Hey, @vanboom, can you rebase this branch with master, please?

**Comment by vanboom** [comment]
Ok, I think I did that right ;)

**Comment by nikolalsvk** [comment]
Thanks for this, @vanboom. Sorry for nitpicking, but could you [squash your commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) to have more descriptive commit messages. Right now we have 14 commits and they are doubled from what I see.

**Comment by vanboom** [comment]
Ok, I think I did that correctly.  Muddling a bit through lack of experience with PRs, thanks for being gracious with these.

**Pull request merged**
