### PR TITLE
Adding CHANGELOG.md

### PR DESCRIPTION
**Pull request by gil27**
This PR addresses Issue #44 

My idea here was to get all Pull Requests between two releases and list them with who opened the pull request

### CODE REVIEW

**Comment by nikolalsvk** [comment]
Thanks @gil27! 

Everyhing you did so far is amazing. Can you also check versions from 0.4.0 to 2.0.0 please? :) I don't see them in your changes.

**Comment by gil27** [comment]
@nikolalsvk, for sure I can. I just looked at releases tab. My fault.

**Comment by nikolalsvk** [comment]
Awesome @gil27, thank you so much for this! 🍰

**Comment by alainravet** [comment]
@gil27 @nikolalsvk 
Any breaking changes from 1.2.0 -> 1.3.0 -> 2.0 ?

**Comment by nikolalsvk** [comment]
Hey @alainravet, there is one possible breaking change if you are dependent on jQuery.

### POSSIBLE BREAKING CHANGE
render_async now renders the usual, non-jQuery JavaScript code to fetch your AJAX requests and
show content on the page.

If you for some reason need jQuery part of render_async, you must configure render_async:

```rb
RenderAsync.configure do |config|
  config.jquery = true
end
```

**Pull request merged**
