### PR TITLE
Improvements and fixes for cached view

### PR DESCRIPTION
**Pull request by nightsurge**
Confession: I was unable to test my changes from prior pull request until last night.

I've made a few discoveries that were preventing things from working as intended. This new pull request is fully working for me now in my own project 💯

### CODE REVIEW

**Comment by nikolalsvk** [comment]
I'll try it out

**Comment by nikolalsvk** [comment]
@nightsurge How would cache expiration work?

**Comment by nikolalsvk** [comment]
Added info on how can you set cache expiration in the README and released the gem version

https://rubygems.org/gems/render_async/versions/0.3.3

**Comment by nightsurge** [comment]
Looks like you found it :) it just uses your global policy by default (from application/development/production.rb) or accepts the expires_in parameter in the view like you added to the README

**Comment by nightsurge** [comment]
Also, I'm the same user as surgevelocityllc (personal vs private accounts). Thanks for making me a contributor!

**Comment by nikolalsvk** [comment]
Yeah, just passed in `expires_in` and it worked. This isn't documented explicitly in documentation for `cache` method.

I've added @nightsurge as contributing account. Cheers! 🍻

**Pull request merged**
