### PR TITLE
Fix: "Uncaught ReferenceError: _interval" #92

### PR DESCRIPTION
**Pull request by fffx**

### CODE REVIEW

**Comment by nikolalsvk** [comment]
Thank you @fffx! 🍰

**Comment by gradybarrett** [comment]
Hey @nikolalsvk, what's the ETA on releasing this?

**Comment by nikolalsvk** [comment]
Hey @gradybarrett, I'll try to do it over the weekend.

**Comment by nikolalsvk** [comment]
I've just released new version 2.1.3! Feel free to check if everything is OK https://rubygems.org/gems/render_async/versions/2.1.3

**Pull request merged**
